version: '3.8'

name: telegram-ai-bot

services:
  telegram-ai-bot-service:
    image: eclipse-temurin:25-alpine
    container_name: telegram-ai-bot
    restart: always
    working_dir: /app
    volumes:
      - ./src/main/resources/application.properties:/app/application.properties
      - ./src/main/resources/logback-spring.xml:/app/logback-spring.xml
      - ./target/telegram-ai-bot-0.0.1.jar:/app/telegram-ai-bot-0.0.1.jar
    command: java -cp /app:/app/* -Dlogging.config=/app/logback-spring.xml -jar /app/telegram-ai-bot-0.0.1.jar
